export const SELECTED_IMAGE = 'SELECTED_IMAGE';
export const FLICKR_IMAGES_SUCCESS = 'FLICKR_IMAGES_SUCCESS';
export const UNSPLASH_IMAGES_REQUEST = 'UNSPLASH_IMAGES_REQUEST';
export const UNSPLASH_IMAGES_SUCCESS = 'UNSPLASH_IMAGES_SUCCESS';
export const FLICKR_IMAGES_REQUEST = 'FLICKR_IMAGES_REQUEST';
export const SHUTTERSTOCK_IMAGES_REQUEST= 'SHUTTERSTOCK_IMAGES_REQUEST';

// export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
