export const LOAD_IMAGES_SUCCESS = 'LOAD_IMAGES_SUCCESS';
//export const LOAD_IMAGES_REQUEST = 'LOAD_IMAGES_REQUEST';
export const SELECTED_IMAGE = 'SELECTED_IMAGE';
export const LOAD_IMAGES_FROM_UNSPLASH = 'LOAD_IMAGES_FROM_UNSPLASH';
export const LOAD_IMAGES_FROM_FLICKR = 'LOAD_IMAGES_FROM_FLICKR';
export const LOAD_IMAGES_FROM_SHUTTERSTOCK= 'LOAD_IMAGES_FROM_SHUTTERSTOCK';

// export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
