export const LOAD_IMAGES_SUCCESS = 'LOAD_IMAGES_SUCCESS';
export const LOAD_IMAGES_REQUEST = 'LOAD_IMAGES_REQUEST';
export const SELECTED_IMAGE = 'SELECTED_IMAGE';

// export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
